import { StyleSheet, Platform } from 'react-native';

const styles = StyleSheet.create({
  webRootWrapper: {
    flex: 1,
    backgroundColor: "#07111f",
    width: "100%",
    overflow: "hidden",
    ...(Platform.OS === 'web' ? { 
      height: '100vh',
      maxHeight: '100vh',
    } : {}),
  },
  appShell: {
    flex: 1,
    backgroundColor: "#07111f",
    width: "100%",
    overflow: "hidden",
  },
  container: {
    flex: 1,
    backgroundColor: "#07111f",
    width: "100%",
    overflow: "hidden",
  },
  stage: {
    flex: 1,
    position: "relative",
    backgroundColor: "#07111f",
    overflow: "hidden",
    ...(Platform.OS === 'web' ? {
      width: '100vw',
      maxWidth: '100vw',
      height: '100vh',
      maxHeight: '100vh',
    } : {}),
  },
  video: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: "100%",
    height: "100%",
    backgroundColor: "#000",
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(7, 17, 31, 0.45)",
  },
  appTopBar: {
    position: "absolute",
    top: 18,
    left: 16,
    right: 16,
    zIndex: 3,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  topBarLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  topBarBack: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 16,
    backgroundColor: "rgba(7, 17, 31, 0.62)",
    borderWidth: 1,
    borderColor: "rgba(143, 200, 255, 0.22)",
  },
  topBarBackText: {
    color: "#dbe8ff",
    fontWeight: "700",
  },
  userBadge: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 16,
    backgroundColor: "rgba(7, 17, 31, 0.62)",
    borderWidth: 1,
    borderColor: "rgba(143, 200, 255, 0.22)",
  },
  userBadgeEyebrow: {
    color: "#95a7bf",
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  userBadgeName: {
    color: "#f8fbff",
    fontSize: 14,
    fontWeight: "700",
    marginTop: 2,
  },
  logoutButton: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 16,
    backgroundColor: "rgba(7, 17, 31, 0.62)",
    borderWidth: 1,
    borderColor: "rgba(143, 200, 255, 0.22)",
  },
  logoutButtonText: {
    color: "#dbe8ff",
    fontWeight: "700",
  },
  storyTopMenuWrap: {
    position: "absolute",
    right: 16,
    zIndex: 6,
  },
  storyMenuButton: {
    width: 48,
    height: 48,
    borderRadius: 18,
    backgroundColor: "rgba(7, 17, 31, 0.68)",
    borderWidth: 1,
    borderColor: "rgba(143, 200, 255, 0.22)",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    shadowColor: "#000",
    shadowOpacity: 0.22,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
  },
  storyMenuLine: {
    width: 20,
    height: 2,
    borderRadius: 999,
    backgroundColor: "#f8fbff",
  },
  storyActionMenu: {
    position: "absolute",
    right: 16,
    zIndex: 6,
    width: 260,
    padding: 14,
    borderRadius: 24,
    backgroundColor: "rgba(8, 15, 31, 0.92)",
    borderWidth: 1,
    borderColor: "rgba(143, 200, 255, 0.18)",
    shadowColor: "#000",
    shadowOpacity: 0.24,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
  },
  storyActionMenuTitle: {
    color: "#97a9c8",
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 1.2,
    fontWeight: "900",
    marginBottom: 10,
  },
  storyActionMenuItem: {
    padding: 14,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    marginTop: 10,
  },
  storyActionMenuDangerItem: {
    backgroundColor: "rgba(255, 91, 127, 0.12)",
    borderColor: "rgba(255, 91, 127, 0.28)",
  },
  storyActionMenuItemTitle: {
    color: "#f8fbff",
    fontSize: 16,
    fontWeight: "900",
  },
  storyActionMenuDangerTitle: {
    color: "#ff9caf",
    fontSize: 16,
    fontWeight: "900",
  },
  storyActionMenuItemSubtext: {
    marginTop: 5,
    color: "#a8b8cf",
    fontSize: 12,
    lineHeight: 17,
  },
  panel: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    padding: 20,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    backgroundColor: "rgba(9, 19, 36, 0.62)",
    borderWidth: 1,
    borderColor: "rgba(148, 194, 255, 0.22)",
  },
  panelFloating: {
    backgroundColor: "rgba(9, 19, 36, 0.52)",
  },
  panelDocked: {
    backgroundColor: "rgba(9, 19, 36, 0.66)",
  },
  kicker: {
    color: "#75d7ff",
    textTransform: "uppercase",
    letterSpacing: 1.2,
    fontSize: 11,
    fontWeight: "700",
  },
  title: {
    marginTop: 8,
    fontSize: 24,
    fontWeight: "800",
    color: "#f8fbff",
  },
  subtitle: {
    marginTop: 10,
    fontSize: 15,
    lineHeight: 22,
    color: "#d0ddf3",
  },
  storyRow: {
    marginTop: 14,
    flexDirection: "row",
    gap: 10,
  },
  storyButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(148, 194, 255, 0.24)",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
  },
  storyButtonActive: {
    backgroundColor: "rgba(58, 211, 255, 0.18)",
    borderColor: "rgba(58, 211, 255, 0.58)",
  },
  storyButtonText: {
    color: "#c8d8ef",
    fontWeight: "700",
    fontSize: 13,
  },
  storyButtonTextActive: {
    color: "#f8fbff",
  },
  optionList: {
    marginTop: 16,
    gap: 12,
  },
  optionButton: {
    paddingVertical: 15,
    paddingHorizontal: 16,
    borderRadius: 16,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(148, 194, 255, 0.26)",
  },
  optionText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#f8fbff",
  },
  primaryButton: {
    marginTop: 18,
    paddingVertical: 16,
    borderRadius: 18,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 8,
  },
  primaryButtonText: {
    fontWeight: "900",
    fontSize: 16,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  outcomeReplayButton: {
    position: "absolute",
    right: 16,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 16,
    backgroundColor: "rgba(7, 17, 31, 0.62)",
    borderWidth: 1,
    borderColor: "rgba(143, 200, 255, 0.22)",
  },
  outcomeReplayText: {
    color: "#f8fbff",
    fontWeight: "800",
    fontSize: 14,
  },
  selfieScreenRoot: {
    flex: 1,
    backgroundColor: "#000",
  },
  selfiePermissionRoot: {
    paddingHorizontal: 24,
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
  },
  selfieLoadingText: {
    marginTop: 12,
    fontSize: 15,
    fontWeight: "700",
  },
  selfieScreenTitle: {
    fontSize: 30,
    fontWeight: "900",
    textAlign: "center",
  },
  selfieScreenText: {
    maxWidth: 360,
    fontSize: 15,
    lineHeight: 23,
    textAlign: "center",
  },
  selfieTopBar: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
    paddingHorizontal: 18,
    paddingBottom: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  selfieBackButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.12)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.25)",
    gap: 6,
  },
  selfieBackButtonText: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "800",
  },
  selfieTopCopy: {
    flex: 1,
  },
  selfieTopEyebrow: {
    fontSize: 11,
    letterSpacing: 1.2,
    textTransform: "uppercase",
    fontWeight: "900",
  },
  selfieTopTitle: {
    marginTop: 3,
    fontSize: 21,
    fontWeight: "900",
  },
  selfieCameraShell: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#000",
  },
  selfieCamera: {
    flex: 1,
  },
  selfiePreviewImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
    transform: [{ scaleX: -1 }],
  },
  selfieControlPanel: {
    position: "absolute",
    left: 16,
    right: 16,
    zIndex: 10,
    paddingHorizontal: 24,
    borderRadius: 32,
    borderWidth: 1,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 8,
  },
  selfiePanelToggle: {
    alignItems: "center",
    justifyContent: "center",
  },
  selfiePanelToggleText: {
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  selfieStatusTitle: {
    fontSize: 20,
    fontWeight: "900",
  },
  selfieStatusText: {
    marginTop: 6,
    fontSize: 14,
    lineHeight: 21,
  },
  selfieCaptureButton: {
    alignSelf: "center",
    marginTop: 18,
    width: 76,
    height: 76,
    borderRadius: 38,
    borderWidth: 4,
    borderColor: "#f8fbff",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  selfieCaptureButtonDisabled: {
    opacity: 0.55,
  },
  selfieCaptureButtonInner: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: "#f8fbff",
  },
  selfieActionRow: {
    marginTop: 18,
    flexDirection: "row",
    gap: 12,
  },
  selfiePrimaryAction: {
    paddingVertical: 15,
    paddingHorizontal: 18,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  selfieAnalyzeAction: {
    flex: 1,
  },
  selfiePrimaryActionText: {
    fontSize: 14,
    fontWeight: "900",
  },
  selfieSecondaryAction: {
    flex: 0.8,
    paddingVertical: 15,
    paddingHorizontal: 18,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  selfieSecondaryActionText: {
    color: "#f8fbff",
    fontSize: 14,
    fontWeight: "900",
  },
  selfieGhostAction: {
    paddingVertical: 12,
    paddingHorizontal: 18,
  },
  selfieGhostActionText: {
    fontSize: 14,
    fontWeight: "800",
  },
  authRoot: {
    flex: 1,
    backgroundColor: "#07111f",
  },
  authScroll: {
    flex: 1,
  },
  authBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#07111f",
    zIndex: 0,
  },
  orbOne: {
    position: "absolute",
    top: -80,
    right: -20,
    width: 260,
    height: 260,
    borderRadius: 999,
    backgroundColor: "rgba(31, 196, 255, 0.2)",
  },
  orbTwo: {
    position: "absolute",
    bottom: 40,
    left: -40,
    width: 220,
    height: 220,
    borderRadius: 999,
    backgroundColor: "rgba(255, 147, 76, 0.18)",
  },
  orbThree: {
    position: "absolute",
    top: "35%",
    left: "42%",
    width: 120,
    height: 120,
    borderRadius: 999,
    backgroundColor: "rgba(111, 83, 255, 0.12)",
  },
  gridGlow: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.28,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: "rgba(143, 200, 255, 0.08)",
  },
  authLayout: {
    flexGrow: 1,
    paddingHorizontal: 20,
    gap: 24,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 2,
    elevation: 2,
  },
  authLayoutWide: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  authLayoutStack: {
    width: "100%",
    justifyContent: "flex-start",
  },
  heroColumn: {
    gap: 16,
    width: "100%",
    maxWidth: 560,
  },
  heroColumnWide: {
    flex: 1,
    maxWidth: 520,
    paddingRight: 20,
  },
  brandChip: {
    alignSelf: "flex-start",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(143, 200, 255, 0.18)",
  },
  brandChipText: {
    color: "#d8e6ff",
    fontSize: 12,
    fontWeight: "700",
  },
  heroTitle: {
    fontSize: Platform.OS === "web" ? 42 : 28,
    lineHeight: Platform.OS === "web" ? 48 : 34,
    color: "#f8fbff",
    fontWeight: "900",
    maxWidth: 560,
  },
  heroSubtitle: {
    maxWidth: 560,
    fontSize: 16,
    lineHeight: 24,
    color: "#b8c7df",
  },
  heroStats: {
    marginTop: 8,
    flexDirection: "row",
    gap: 12,
    flexWrap: "wrap",
  },
  statCard: {
    minWidth: 110,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 18,
    backgroundColor: "rgba(255, 255, 255, 0.07)",
    borderWidth: 1,
    borderColor: "rgba(143, 200, 255, 0.16)",
  },
  statNumber: {
    color: "#f8fbff",
    fontSize: 18,
    fontWeight: "800",
  },
  statLabel: {
    marginTop: 4,
    color: "#9cb0cb",
    fontSize: 12,
  },
  formScene: {
    position: "relative",
    justifyContent: "center",
    width: "100%",
    maxWidth: 520,
    zIndex: 4,
    elevation: 4,
  },
  cardShadowLayer: {
    position: "absolute",
    top: 22,
    left: 16,
    right: -6,
    bottom: -14,
    borderRadius: 28,
    backgroundColor: "rgba(1, 10, 20, 0.54)",
    transform: [{ rotate: "-5deg" }],
  },
  cardGlowLayer: {
    position: "absolute",
    top: -6,
    left: -8,
    right: 20,
    bottom: 16,
    borderRadius: 28,
    backgroundColor: "rgba(79, 209, 255, 0.14)",
    transform: [{ rotate: "4deg" }],
  },
  authCard: {
    minHeight: 520,
    width: "100%",
    padding: 22,
    borderRadius: 28,
    backgroundColor: "rgba(11, 22, 40, 0.95)",
    borderWidth: 1.2,
    borderColor: "rgba(143, 200, 255, 0.28)",
    zIndex: 6,
    elevation: 6,
  },
  authSwitch: {
    flexDirection: "row",
    padding: 6,
    borderRadius: 18,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderWidth: 1.2,
    borderColor: "rgba(143, 200, 255, 0.18)",
  },
  authSwitchButton: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 12,
    borderRadius: 14,
  },
  authSwitchButtonActive: {
    backgroundColor: "#4fd1ff",
  },
  authSwitchText: {
    color: "#d8e6ff",
    fontWeight: "700",
  },
  authSwitchTextActive: {
    color: "#06111f",
  },
  authHeading: {
    marginTop: 24,
    fontSize: 28,
    lineHeight: 34,
    color: "#f8fbff",
    fontWeight: "800",
  },
  authSubheading: {
    marginTop: 8,
    color: "#9fb3ce",
    fontSize: 14,
    lineHeight: 22,
  },
  formFields: {
    marginTop: 22,
    gap: 14,
  },
  inputWrap: {
    gap: 8,
  },
  inputLabel: {
    color: "#d8e6ff",
    fontSize: 13,
    fontWeight: "700",
  },
  input: {
    borderRadius: 16,
    backgroundColor: "rgba(255, 255, 255, 0.06)",
    borderWidth: 1,
    borderColor: "rgba(143, 200, 255, 0.18)",
    paddingHorizontal: 16,
    paddingVertical: 15,
    color: "#f8fbff",
    fontSize: 15,
  },
  authPrimaryButton: {
    marginTop: 22,
    paddingVertical: 18,
    borderRadius: 20,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 15,
    elevation: 10,
  },
  authPrimaryButtonText: {
    fontSize: 17,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  authNote: {
    marginTop: 14,
    color: "#94a8c3",
    fontSize: 12,
    lineHeight: 18,
  },
  authMessage: {
    marginTop: 12,
    color: "#ffd5b3",
    fontSize: 13,
    lineHeight: 18,
  },
  loadingScreen: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#07111f",
    gap: 14,
  },
  loadingText: {
    color: "#d8e6ff",
    fontSize: 15,
    fontWeight: "600",
  },
  dashboardRoot: {
    flex: 1,
    overflow: "hidden",
  },
  dashboardBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  dashboardGlowOne: {
    position: "absolute",
    top: -100,
    right: -80,
    width: 350,
    height: 350,
    borderRadius: 999,
  },
  dashboardGlowTwo: {
    position: "absolute",
    bottom: -60,
    left: -100,
    width: 320,
    height: 320,
    borderRadius: 999,
  },
  dashboardScroll: {
    flex: 1,
  },
  dashboardContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
  },
  dashboardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  dashboardIdentity: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flexShrink: 1,
  },
  dashboardIdentityCompact: {
    gap: 10,
  },
  dashboardIdentityText: {
    flexShrink: 1,
    minWidth: 0,
  },
  avatarCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "rgba(255,255,255,0.1)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(190, 153, 255, 0.4)",
  },
  avatarText: {
    color: "#f8fbff",
    fontSize: 20,
    fontWeight: "900",
  },
  avatarCircleCompact: {
    width: 42,
    height: 42,
    borderRadius: 21,
  },
  avatarTextCompact: {
    fontSize: 17,
  },
  dashboardName: {
    color: "#b78cff",
    fontSize: 22,
    fontWeight: "900",
    fontStyle: "italic",
  },
  dashboardNameCompact: {
    fontSize: 18,
  },
  dashboardTag: {
    color: "#9ba9c3",
    fontSize: 12,
    marginTop: 2,
  },
  dashboardTagCompact: {
    fontSize: 11,
  },
  sideMenuBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(3, 8, 18, 0.52)",
    zIndex: 8,
  },
  sideMenuPanel: {
    position: "absolute",
    top: 0,
    left: 0,
    bottom: 0,
    width: 286,
    paddingTop: 58,
    paddingHorizontal: 18,
    paddingBottom: 24,
    backgroundColor: "#0c1530",
    borderRightWidth: 1,
    borderRightColor: "rgba(143, 167, 255, 0.2)",
    zIndex: 9,
    overflow: "hidden",
  },
  sideMenuPanelExpanded: {
    borderRightWidth: 0,
  },
  sideMenuGlowTop: {
    position: "absolute",
    top: -20,
    right: -40,
    width: 180,
    height: 180,
    borderRadius: 999,
    backgroundColor: "rgba(140, 102, 255, 0.22)",
  },
  sideMenuGlowBottom: {
    position: "absolute",
    bottom: -30,
    left: -50,
    width: 180,
    height: 180,
    borderRadius: 999,
    backgroundColor: "rgba(72, 200, 255, 0.14)",
  },
  sideMenuHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 14,
    marginBottom: 12,
    borderRadius: 24,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1.2,
    borderColor: "rgba(255,255,255,0.12)",
  },
  sideMenuAvatarShell: {
    width: 68,
    height: 68,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  sideMenuAvatar: {
    width: 52,
    height: 52,
    borderRadius: 18,
    backgroundColor: "rgba(155, 109, 255, 0.85)",
    alignItems: "center",
    justifyContent: "center",
  },
  sideMenuAvatarText: {
    color: "#f8fbff",
    fontSize: 22,
    fontWeight: "900",
  },
  sideMenuUserInfo: {
    flex: 1,
  },
  sideMenuEyebrow: {
    color: "#97a9c8",
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 1.1,
    fontWeight: "800",
  },
  sideMenuName: {
    color: "#f8fbff",
    fontSize: 18,
    fontWeight: "800",
    marginTop: 4,
  },
  sideMenuEmail: {
    marginTop: 4,
    color: "#b8c7df",
    fontSize: 12,
  },
  sideMenuBody: {
    flex: 1,
    paddingTop: 22,
    minHeight: 0,
  },
  sideMenuBodyContent: {
    gap: 12,
    paddingBottom: 20,
    flexGrow: 1,
  },
  sideMenuSectionTitle: {
    color: "#93a4c4",
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 1.2,
    fontWeight: "800",
    marginBottom: 4,
  },
  sideMenuItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1.2,
    borderColor: "rgba(255,255,255,0.1)",
  },
  sideMenuItemBody: {
    flex: 1,
  },
  sideMenuItemText: {
    color: "#eef2ff",
    fontSize: 15,
    fontWeight: "700",
  },
  sideMenuItemSubtext: {
    marginTop: 3,
    color: "#90a4c4",
    fontSize: 12,
    lineHeight: 17,
  },
  sideMenuSettingsHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    marginBottom: 20,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.08)",
  },
  sideMenuBackButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  sideMenuBackButtonText: {
    color: "#eef2ff",
    fontSize: 12,
    fontWeight: "800",
  },
  sideMenuSettingsTitle: {
    color: "#f8fbff",
    fontSize: 22,
    fontWeight: "900",
    letterSpacing: -0.5,
    flex: 1,
  },
  sideMenuInfoCard: {
    marginTop: 4,
    padding: 18,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1.2,
    borderColor: "rgba(255,255,255,0.1)",
  },
  sideMenuInfoTitle: {
    color: "#f8fbff",
    fontSize: 18,
    fontWeight: "800",
  },
  sideMenuInfoText: {
    marginTop: 10,
    color: "#a6b6d2",
    fontSize: 14,
    lineHeight: 22,
  },
  historyStateCard: {
    marginTop: 16,
    padding: 16,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    gap: 10,
  },
  historyStateText: {
    color: "#d8e2f1",
    fontSize: 14,
    lineHeight: 20,
  },
  historyList: {
    marginTop: 16,
    gap: 12,
  },
  historyItem: {
    padding: 16,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  historyItemTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  historyItemType: {
    color: "#f8fbff",
    fontSize: 15,
    fontWeight: "800",
    flex: 1,
  },
  historyItemDate: {
    color: "#97a9c8",
    fontSize: 12,
    fontWeight: "700",
  },
  historyItemMessage: {
    marginTop: 10,
    color: "#dbe6f6",
    fontSize: 14,
    lineHeight: 20,
  },
  historyItemMeta: {
    marginTop: 8,
    color: "#8fa1bf",
    fontSize: 12,
    lineHeight: 18,
  },
  storyLaunchList: {
    marginTop: 16,
    gap: 12,
  },
  storyLaunchCard: {
    padding: 16,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  storyLaunchCardSelected: {
    backgroundColor: "rgba(159, 107, 255, 0.18)",
    borderColor: "rgba(159, 107, 255, 0.5)",
  },
  storyLaunchTextWrap: {
    flex: 1,
  },
  storyLaunchTitle: {
    color: "#f8fbff",
    fontSize: 16,
    fontWeight: "800",
  },
  storyLaunchSubtitle: {
    marginTop: 6,
    color: "#a6b6d2",
    fontSize: 13,
    lineHeight: 18,
  },
  storyLaunchAction: {
    color: "#9f6bff",
    fontSize: 13,
    fontWeight: "900",
  },
  storyModePreferenceNote: {
    marginTop: 16,
    color: "#a6b6d2",
    fontSize: 12,
    lineHeight: 18,
  },
  randomStoryLaunchButton: {
    marginTop: 16,
    paddingVertical: 14,
    borderRadius: 18,
    backgroundColor: "rgba(159, 107, 255, 0.2)",
    borderWidth: 1,
    borderColor: "rgba(159, 107, 255, 0.4)",
    alignItems: "center",
  },
  randomStoryLaunchText: {
    color: "#f3ecff",
    fontSize: 14,
    fontWeight: "800",
  },
  themeSettingsCard: {
    marginTop: 4,
    padding: 14,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  themeSettingsTitle: {
    color: "#f8fbff",
    fontSize: 16,
    fontWeight: "800",
  },
  themeSettingsSubtitle: {
    marginTop: 6,
    color: "#a6b6d2",
    fontSize: 12,
    lineHeight: 18,
  },
  themeToggleRow: {
    marginTop: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  themeToggleTextWrap: {
    flex: 1,
  },
  themeToggleLabel: {
    color: "#eef2ff",
    fontSize: 14,
    fontWeight: "700",
  },
  themeToggleHint: {
    marginTop: 4,
    color: "#8fa1bf",
    fontSize: 11,
    lineHeight: 16,
  },
  themeToggle: {
    width: 52,
    height: 30,
    borderRadius: 999,
    padding: 4,
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.14)",
  },
  themeToggleActive: {
    backgroundColor: "rgba(90, 240, 194, 0.32)",
  },
  themeToggleKnob: {
    width: 22,
    height: 22,
    borderRadius: 999,
    backgroundColor: "#f8fbff",
  },
  themeToggleKnobActive: {
    alignSelf: "flex-end",
  },
  appearanceSection: {
    marginTop: 16,
  },
  appearanceSectionTitle: {
    color: "#eef2ff",
    fontSize: 14,
    fontWeight: "700",
  },
  appearanceSectionHint: {
    marginTop: 4,
    color: "#8fa1bf",
    fontSize: 11,
    lineHeight: 16,
  },
  appearanceChipWrap: {
    marginTop: 12,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  appearanceChip: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  appearanceChipActive: {
    backgroundColor: "rgba(159, 107, 255, 0.18)",
    borderColor: "rgba(159, 107, 255, 0.5)",
  },
  appearanceChipText: {
    color: "#eef2ff",
    fontSize: 12,
    fontWeight: "700",
  },
  appearanceChipTextActive: {
    color: "#ffffff",
  },
  themeChipWrap: {
    marginTop: 14,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  themeChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth: 1,
  },
  themeChipDot: {
    width: 10,
    height: 10,
    borderRadius: 999,
  },
  themeChipText: {
    color: "#eef2ff",
    fontSize: 12,
    fontWeight: "700",
  },
  sideMenuFooter: {
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: "rgba(143, 167, 255, 0.12)",
  },
  sideMenuLogoutButton: {
    paddingVertical: 15,
    borderRadius: 18,
    alignItems: "center",
    borderWidth: 1.2,
    backgroundColor: "rgba(255, 123, 123, 0.15)",
    borderColor: "rgba(255, 123, 123, 0.4)",
  },
  sideMenuLogoutText: {
    color: "#2d0d0d",
    fontSize: 15,
    fontWeight: "900",
  },
  storyProfileMenu: {
    position: "absolute",
    right: 16,
    zIndex: 5,
    minWidth: 220,
    padding: 12,
    borderRadius: 18,
    backgroundColor: "rgba(10, 16, 34, 0.95)",
    borderWidth: 1,
    borderColor: "rgba(143, 167, 255, 0.16)",
  },
  storyThemeSettingsWrap: {
    marginBottom: 10,
  },
  profileMenuEmail: {
    color: "#c7d4ee",
    fontSize: 13,
    marginBottom: 10,
  },
  profileMenuItem: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.06)",
  },
  profileMenuItemText: {
    color: "#f8fbff",
    fontWeight: "800",
  },
  dashboardHero: {
    marginTop: 22,
    marginBottom: 20,
    paddingVertical: 18,
    paddingHorizontal: 18,
    borderRadius: 24,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  dashboardHeroTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  dashboardHeroEyebrow: {
    color: "#9ba9c3",
    textTransform: "uppercase",
    letterSpacing: 1.3,
    fontSize: 12,
    fontWeight: "900",
  },
  dashboardHeroTitleSmall: {
    marginTop: 6,
    color: "#eef2ff",
    fontSize: 28,
    lineHeight: 34,
    fontWeight: "900",
    maxWidth: 520,
  },
  dashboardHeroTitleSmallCompact: {
    fontSize: 22,
    lineHeight: 28,
    maxWidth: 320,
  },
  dashboardHeroText: {
    marginTop: 14,
    color: "#b7c3db",
    fontSize: 15,
    lineHeight: 24,
    maxWidth: 680,
  },
  dashboardGrid: {
    gap: 18,
    paddingBottom: 20,
  },
  dashboardGridWide: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  dashboardCard: {
    width: "100%",
    borderRadius: 24,
    padding: 24,
    borderWidth: 1.2,
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 15,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  selfieCard: {
    overflow: "hidden",
  },
  storyCard: {
    backgroundColor: "#16213f",
  },
  dashboardCardLabel: {
    color: "#9d8cff",
    textTransform: "uppercase",
    letterSpacing: 1.2,
    fontSize: 11,
    fontWeight: "800",
  },
  dashboardCardTitle: {
    marginTop: 10,
    color: "#f4f7ff",
    fontSize: 24,
    lineHeight: 30,
    fontWeight: "800",
  },
  dashboardCardText: {
    marginTop: 10,
    color: "#b3c0d9",
    fontSize: 15,
    lineHeight: 22,
  },
  moodRow: {
    marginTop: 20,
    flexDirection: "row",
    gap: 12,
  },
  moodButton: {
    flex: 1,
    minHeight: 86,
    borderRadius: 18,
    backgroundColor: "#1b2748",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
  moodButtonActive: {
    backgroundColor: "#b78cff",
    borderColor: "#d1b0ff",
  },
  moodEmoji: {
    fontSize: 28,
  },
  moodLabel: {
    marginTop: 6,
    color: "#d6e0f8",
    fontSize: 12,
    fontWeight: "700",
  },
  moodLabelActive: {
    color: "#0d1330",
  },
  selfieFrame: {
    height: 220,
    borderRadius: 20,
    marginBottom: 14,
    backgroundColor: "#223056",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  selfieBadge: {
    position: "absolute",
    top: 12,
    left: 12,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "rgba(7,13,31,0.76)",
  },
  selfieBadgeText: {
    color: "#eef2ff",
    fontSize: 11,
    fontWeight: "700",
  },
  selfieFace: {
    fontSize: 94,
  },
  secondaryAction: {
    marginTop: 16,
    alignSelf: "flex-start",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 16,
    backgroundColor: "rgba(183, 140, 255, 0.16)",
    borderWidth: 1,
    borderColor: "rgba(183, 140, 255, 0.36)",
  },
  secondaryActionText: {
    color: "#efe3ff",
    fontWeight: "800",
  },
  storyAction: {
    marginTop: 18,
    paddingVertical: 15,
    borderRadius: 18,
    backgroundColor: "#4cc3ff",
    alignItems: "center",
  },
  storyActionText: {
    color: "#06111f",
    fontSize: 15,
    fontWeight: "900",
  },
  feedbackInput: {
    marginTop: 16,
    minHeight: 150,
    borderRadius: 18,
    backgroundColor: "#1b2748",
    paddingHorizontal: 16,
    paddingVertical: 16,
    color: "#eef2ff",
    textAlignVertical: "top",
    fontSize: 15,
  },
  feedbackCount: {
    marginTop: 8,
    alignSelf: "flex-end",
    color: "#93a4c4",
    fontSize: 12,
  },
  primaryDashboardAction: {
    marginTop: 16,
    paddingVertical: 16,
    borderRadius: 20,
    backgroundColor: "#9b6dff",
    alignItems: "center",
  },
  primaryDashboardActionText: {
    color: "#10162f",
    fontWeight: "900",
    letterSpacing: 1,
  },
  emotionResultCard: {
    marginTop: 18,
    padding: 18,
    borderRadius: 22,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    alignItems: "center",
    gap: 8,
  },
  emotionEmoji: {
    fontSize: 52,
  },
  emotionLabel: {
    fontSize: 20,
    fontWeight: "900",
    textTransform: "capitalize",
  },
  emotionConfidence: {
    fontSize: 13,
    fontWeight: "700",
  },
  feedbackResultBanner: {
    marginTop: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 16,
    width: "100%",
  },
  feedbackResultLabel: {
    fontSize: 16,
    fontWeight: "700",
  },
  feedbackResultValue: {
    fontSize: 22,
    fontWeight: "900",
    textTransform: "capitalize",
  },
  selfieWebView: {
    position: "absolute",
    width: 0,
    height: 0,
    opacity: 0,
  },
  animScreenRoot: {
    flex: 1,
    backgroundColor: "#07111f",
  },
  animBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  animGlowTop: {
    position: "absolute",
    top: -60,
    right: -40,
    width: 300,
    height: 300,
    borderRadius: 999,
  },
  animGlowBottom: {
    position: "absolute",
    bottom: -40,
    left: -60,
    width: 260,
    height: 260,
    borderRadius: 999,
  },
  animContent: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 28,
    gap: 20,
  },
  animParticleWrap: {
    ...StyleSheet.absoluteFillObject,
    overflow: "hidden",
  },
  animParticle: {
    position: "absolute",
  },
  animEmojiWrap: {
    alignItems: "center",
    justifyContent: "center",
    width: 140,
    height: 140,
    marginBottom: 8,
  },
  animEmojiGlow: {
    position: "absolute",
    width: 140,
    height: 140,
    borderRadius: 70,
  },
  animEmojiText: {
    fontSize: 80,
  },
  animTitle: {
    fontSize: 34,
    fontWeight: "900",
    textAlign: "center",
  },
  animSubtitle: {
    fontSize: 16,
    lineHeight: 24,
    textAlign: "center",
    maxWidth: 340,
  },
  animFeedbackBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 20,
    marginTop: 8,
  },
  animFeedbackLabel: {
    fontSize: 16,
    fontWeight: "700",
  },
  animFeedbackValue: {
    fontSize: 24,
    fontWeight: "900",
  },
  animDoneButton: {
    marginTop: 24,
    paddingVertical: 16,
    paddingHorizontal: 40,
    borderRadius: 20,
    alignItems: "center",
  },
  animDoneButtonText: {
    fontSize: 16,
    fontWeight: "900",
  },
  // --- Welcome Animation Styles (Coral Theme) ---
  introRoot: {
    ...StyleSheet.absoluteFillObject,
    overflow: "hidden",
    zIndex: 9999,
    backgroundColor: "#07111f",
  },
  introGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  introCircle: {
     position: 'absolute',
     borderRadius: 1000,
     overflow: 'hidden',
     borderWidth: 2,
     borderColor: 'rgba(255,255,255,0.2)',
  },
  introCircleImage: {
    width: '100%',
    height: '100%',
  },
  introBottomContent: {
    position: 'absolute',
    bottom: 60,
    left: 30,
    right: 30,
  },
  introLargeText: {
    fontSize: 58,
    fontWeight: '900',
    color: '#FFFFFF',
    lineHeight: 62,
    marginBottom: 40,
  },
  introLoaderContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    height: 60,
  },
  introDot: {
    position: 'absolute',
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#FFFFFF',
  },
});

export default styles;
